[package]
name = "music-compressor"
version = "2.0.0"
authors = ["zerfix <zerfix@protonmail.com>"]
edition = "2018"

[dependencies]
dotenv      = "0.15.0" # env
lazy_static = "1.4.0"  # static conf
notify      = "4.0.15" # filesystem listener
