version: "3"

services:
    compressor:
        build: .
        container_name: compressor
        environment:
            - INPUT_DIR=/input
            - OUTPUT_DIR=/output
        volumes:
          - /tmp/input:/input:ro
          - /tmp/output:/output
